import type { Metadata } from "next";
import { bebasNeue, dmMono, dmSans } from '@/app/fonts/fonts'
import "./globals.css";
import NavBar from "./components/navbar/NavBar";
import Footer from "./components/footer/Footer";
import NextTopLoader from 'nextjs-toploader';

export const metadata: Metadata = {
  title: "Carology",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${bebasNeue.variable} ${dmMono.variable} ${dmSans.variable} antialiased flex flex-col min-h-screen`}
      >
        <NextTopLoader showSpinner={false} />
        <NavBar/>
        <div className="bg-cream">
          {children}
        </div>
      <Footer/>
      </body>
    </html>
  );
}
