import type { Metadata } from "next";
import {Inter} from 'next/font/google'
import "./globals.css";
import NavBar from "./components/navbar/NavBar";
import Footer from "./components/footer/Footer";

export const inter = Inter({
  subsets: ['latin'],
})

export const metadata: Metadata = {
  title: "Carology",
  description: "Generated by create next app",
};



export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.className} flex flex-col min-h-screen`}
      >
        <NavBar/>
        <div className="flex-1 pt-24 px-6">
          {children}
        </div>
      <Footer/>
      </body>
    </html>
  );
}
